[config]
size = 0.15                 # % of screen
interaction = 10.0          # % of screen
separation_intensity = 2000 # Intensity of separation forces between particles

[config.environment]
color = [0.04, 0.04, 0.08] # black
damping = 2                # % of energy lost to the environment every simulation step

[types.red]
color = [0.95, 0.30, 0.30] # red
population = 4000
density_regulation = true

[types.blue]
color = [0.30, 0.65, 1.00] # blue
population = 4000
density_regulation = true

[types.green]
color = [0.35, 0.90, 0.45] # green
population = 4000
density_regulation = true

[types.yellow]
color = [0.95, 0.80, 0.20] # yellow
population = 4000
density_regulation = true


[presets.blobs]
description = "Larger groups with pursuit behaviour."
matrix = [
  #red,   blue,  green, yellow
  [5.0, 12.0, -1.0, -1.0],  # red
  [-10.0, 5.0, -1.0, 4.0],  # blue
  [-1.0, -1.0, -5.0, 3.0],  # green
  [-0.5, -10.0, 1.0, 10.0], # yellow
]

[presets.overtrust]
description = "Everyone trusts everyone, except equals"
matrix = [
  #red,   blue,  green, yellow
  [-14.0, 4.0, 4.0, 4.0], # red
  [4.0, -14.0, 4.0, 4.0], # blue
  [4.0, 4.0, -14.0, 4.0], # green
  [4.0, 4.0, 4.0, -14.0], # yellow
]

[presets.distrust]
description = "Everyone distrusts everyone, except equals"
matrix = [
  #red,   blue,  green, yellow
  [14.0, -4.0, -4.0, -4.0], # red
  [-4.0, 14.0, -4.0, -4.0], # blue
  [-4.0, -4.0, 14.0, -4.0], # green
  [-4.0, -4.0, -4.0, 14.0], # yellow
]

[presets.cells]
description = "Organic like structures..."
matrix = [
  #red,   blue,  green, yellow
  [10.0, -14.0, -6.0, -1.0], # red
  [14.0, -3.0, 10.0, -10.0], # blue
  [-4.0, 4.0, 0.0, -7.0],    # green
  [-6.0, 11.0, -8.0, 1.0],   # yellow
]

[presets.wip]
description = "In definition..."
matrix = [
  #red,   blue,  green, yellow
  [4.0, 2.0, 0.0, 0.0], # red
  [0.0, 4.0, 2.0, 0.0], # blue
  [0.0, 0.0, 4.0, 2.0], # green
  [2.0, 0.0, 0.0, 4.0], # yellow
]

[presets.cell_competition]
description = "Shell-nucleus cells competing for food"
matrix = [
  #red,   blue,  green, yellow
  [4.0, 13.0, 10.0, 2.0],  # red    (A nucleus)
  [0.0, 4.0, 1.0, 0.0],    # blue   (A shell)
  [-2.0, -2.0, 2.0, -2.0], # green  (food)
  [2.0, 0.0, 10.0, 4.0],   # yellow (B nucleus)
]
