[config]
size = 0.0015
interaction = 0.025

[config.separation]
coefficient = 5000
size = 0.004

[types.red]
color = [0.95, 0.30, 0.30] # red
population = 5000

[types.blue]
color = [0.30, 0.65, 1.00] # blue
population = 5000

[types.green]
color = [0.35, 0.90, 0.45] # green
population = 5000

[types.yellow]
color = [0.95, 0.80, 0.20] # yellow
population = 5000


[presets.cells]
description = "Organic like structures..."
matrix = [
  #red, blue, green, yellow
  [-5.0, -10.0, 1.0, 1.0],  # red
  [10.0, -5.0, 1.0, -4.0],  # blue
  [1.0, 1.0, 5.0, -3.0],    # green
  [0.5, 10.0, -1.0, -10.0], # yellow
]


[presets.overtrust]
description = "Everyone likes everyone, except equals"
matrix = [
  #red, blue, green, yellow
  [14.0, -4.0, -4.0, -4.0], # red
  [-4.0, 14.0, -4.0, -4.0], # blue
  [-4.0, -4.0, 14.0, -4.0], # green
  [-4.0, -4.0, -4.0, 14.0], # yellow
]

[presets.distrust]
description = "Everyone dislikes everyone, except equals"
matrix = [
  #red, blue, green, yellow
  [-14.0, 4.0, 4.0, 4.0], # red
  [4.0, -14.0, 4.0, 4.0], # blue
  [4.0, 4.0, -14.0, 4.0], # green
  [4.0, 4.0, 4.0, -14.0], # yellow
]

[presets.blobs]
description = "Larger groups with pursuit behaviour."
matrix = [
  #red, blue, green, yellow
  [-14.0, 14.0, 6.0, 0.0],   # red
  [-14.0, 3.0, -10.0, 10.0], # blue
  [4.0, -4.0, 0.0, 7.0],     # green
  [6.0, -11.0, 8.0, -10.0],  # yellow
]
